### ISSUE TITLE
Ruins Invalid Data Report - GS141 - M06

### ISSUE THREAD

**Issue by luchasucha** [canonn-science/RuinsComboMap#37] opened 2017-06-18 21:16 UTC
***Please note:*** Tech 6 obelisks have been confirmed to be bugged by Frontier. Mission cannot be completed until Frontier rolls out a fix for that.

## Your CMDR Name:
CMDR lucasaz

## Which Ruins Site?
IC 2391 SECTOR YE-A D103 B 1 YE-A D103 B 1

## Which Obelisk?
M06

## What data did you get?
Technology 14

## What combo did you use?
 Totem + Orb

**Comment by derrickmehaffy** [comment] 2017-06-26 07:41
Per Supafuzz916:
GS141 M06 confirmed as Cult 19 scanned Totem+Orb http://imgur.com/a/trCbA

**Comment by derrickmehaffy** [comment] 2017-06-26 10:54
2 Others have verified the combo on this, Possible multiple combo but unlikely due to different data types, the bulk of this group being Culture makes it highly unlikely a technology data point is here.

**Comment by andybish** [comment] 2017-06-27 10:39
I got Culture 19 from this, on a fresh mission. Repeat scan didn't give Tech 14.

**Comment by derrickmehaffy** [comment] 2017-07-07 12:36
Issue confirmed to have incorrect information by 2 others, marking as resolved

**Closed by derrickmehaffy** 2017-07-07 12:36 UTC
Labels: pending, Ruins Invalid Data
