### ISSUE TITLE
Ruins Invalid Data Report - GS78 - N16

### ISSUE THREAD

**Issue by spongedoc** [canonn-science/RuinsComboMap#27] opened 2017-06-06 20:28 UTC
***Please note:*** Tech 6 obelisks have been confirmed to be bugged by Frontier. Mission cannot be completed until Frontier rolls out a fix for that.

## Your CMDR Name:
spongedoc

## Which Ruins Site?
GS78

## Which Obelisk ID?
ALL in group N

## What data did you get?
Nothing

## What combo did you use?
Nothing

## Other Questions/Comments/Concerns
The whole N group of monoliths is missing.
![20170606222750_1](https://user-images.githubusercontent.com/26961499/26850334-6aee3478-4b07-11e7-99a2-315d15cdc4c5.jpg)

**Comment by derrickmehaffy** [comment] 2017-06-26 07:48
Per Supafuzz916:

GS78. Can confirm there is no N cluster at this ruin. I did the initial survey and Boozeman later confirmed it according to the  active obelisk spreadsheet. Neither of us reported a N cluster at this ruin site. In addition there are other problems with this site. We both reported Clusters D, G, H, M, R at this site. THe map from the API also shows a T cluster and I can confirm that it does not exist either. Also the map does not show the R cluster at all. Might want to take a look at the API info verses the Actives report spreadsheet on this site as it looks like there was a boo-boo when this one got transfered to the API.

Side note, requesting further review of this site to review its data in the API.

**Comment by andybish** [comment] 2017-06-27 17:25
Confirming clusters D G H M and R only at this site. Lit obelisks:
D12
G03, G11
H09
M02
R14, R15

**Comment by derrickmehaffy** [comment] 2017-07-07 12:35
Updated sheet, pending API update, marking as resolved

**Closed by derrickmehaffy** 2017-07-07 12:35 UTC
Labels: help wanted, in progress, Ruins Invalid Data
